### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by akshaybabloo** [azureappserviceoss/DjangoAzure#3]
Hi,

Is there any documentation for the files being used?
- Like what version of Django is supported?
- DB requirements?

The important stuff.

Thanks.

**Comment by aarcro** [comment]
Yeah, any clues would be nice. I launched it, got a test page. Now I'm going to have to read your source to figure out how to run my site.

**Comment by akshaybabloo** [comment]
@aarcro that's why I moved to heroku.

**Comment by aarcro** [comment]
Not an option for me sadly. Hoping Docker based deployment works better, should have more control of my environment that way.

**Comment by akshaybabloo** [comment]
https://www.divio.com/en/ is specifically for that

**Comment by dirkesquire** [comment]
I think this is a great repo and it works very well. I am interested to hear the reasoning for checking the env folder into source control? Normally one does not do this. Why does it make sense here? Does it help with the deployment on Azure? 
One of the first things one wants to do after cloning this repo is to create your own env folder - so is it important to name it differently and keep the existing env folder intact for deployment purposes?
